var student_list = [
    'Juliette',
    'Léo',
    'Nolwenn',
    'Henri',
    'Brieuc',
    'Nicolas G',
    'Célia',
    'Lila',
    'Bilal',
    'Vivien',
    'Erwan',
    'Nicolas D',
    'Martin',
    'Alexis',
    'Tanaïs',
    'Paul',
    'Tristan',
    'Elise',
    'Tanguy',
    'Laetitia',
    'Agathe',
    'Talina',
    'Anaïs',
    'Victor',
    'Amélie',
    'Malo',
    'Barthélemy',
    'Louis',
    'Guillemette',
    'Charlotte',
    'Thomas',
    'Bérénice',
    'Yves-Maël',
    'Astrid',
    'Audren',
];